trigger:
- main

pool: 
  name: Default
  vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'microsoft/windowsservercore'

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
- task: Docker@2
  displayName:  Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile