trigger:
- main

pool: 
  name: Default
  vmImage: 'windows-2019' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'microsoft/windowsservercore'

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 19.03.14
    releaseType: stable
- task: Docker@2
  displayName:  Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile